# Generated by Django 6.0.2 on 2026-03-12 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_juego_descripcion_juego_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleboleta',
            name='boleta',
        ),
        migrations.RemoveField(
            model_name='detalleboleta',
            name='juego',
        ),
        migrations.DeleteModel(
            name='Boleta',
        ),
        migrations.DeleteModel(
            name='DetalleBoleta',
        ),
    ]
